# Generated by Django 4.2 on 2026-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('fecha_publicacion', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
