# Generated by Django 6.1 on 2026-08-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponible',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('DANADO', 'Dañado'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=20),
        ),
    ]
