# Generated by Django 6.1 on 2026-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='disponible',
        ),
        migrations.AddField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('DISPONIBLE', '🟢 Disponible'), ('DANADO', '🟡 Dañado'), ('NO_DISPONIBLE', '🔴 No disponible')], default='DISPONIBLE', max_length=20),
        ),
    ]
