# Generated by Django 6.1 on 2026-10-02 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_rename_pagada_multa_pagado_remove_prestamo_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='año',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_afiliacion',
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
